name: "Microsoft App Center (Linux, Windows, macOS)"
description: "GitHub Action that uploads artifacts for Visual Studio App Center"
author: "Wojciech Zięba <@wzieba> & Coxxs & emertozd"
inputs:
  appName:
    description: "App name followed by username e.g. wzieba/Sample-App"
    required: true
  token:
    description: "Upload token - you can get one from appcenter.ms/settings"
    required: true
  group:
    description: "Distribution group"
    required: true
  file:
    description: "Artefact to upload (.apk or .ipa)"
    required: true
  buildVersion:
    description: "Build version parameter required for .zip, .msi, .pkg and .dmg files"
    required: false
  buildNumber:
    description: "Build number parameter required for macOS .pkg and .dmg files"
    required: false
  releaseNotes:
    description: "Release notes visible on release page"
    required: false
  gitReleaseNotes:
    description: "Generate release notes based on the latest git commit"
    required: false
  notifyTesters:
    description: "If true, send an email notification to the distribution group"
    required: false
  debug:
    description: "If true, shows additional information from the action execution"
    required: false
    default: false
branding:
  color: "red"
  icon: "send"
runs:
  using: "composite"
  steps:
    - name: Install Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install -g appcenter-cli@3.0.1
      shell: bash
    - name: Publish to App Center
      run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_APPNAME: ${{ inputs.appName }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_GROUP: ${{ inputs.group }}
        INPUT_FILE: ${{ inputs.file }}
        INPUT_BUILDVERSION: ${{ inputs.buildVersion }}
        INPUT_BUILDNUMBER: ${{ inputs.buildNumber }}
        INPUT_RELEASENOTES: ${{ inputs.releaseNotes }}
        INPUT_GITRELEASENOTES: ${{ inputs.gitReleaseNotes }}
        INPUT_NOTIFYTESTERS: ${{ inputs.notifyTesters }}
        INPUT_DEBUG: ${{ inputs.debug }}
